export const routes = [
    {
        path:'/',
        name:'Home',
        id:1
    },
    {
        path:'/login',
        name:'Entrar',
        id:2
    },
    {
        path:'/register',
        name:'Cadastrar',
        id:3
    },
    {
        path:'/about',
        name:'Sobre',
        id:4
    },
]